### ISSUE TITLE
review dependency on bcrypt-pbkdf

### ISSUE THREAD

**Issue by Parcley** [joyent/node-sshpk#37]
bcrypt-pbkdf does not include any license information, but if you check 
https://www.npmjs.com/package/bcrypt-pbkdf

the publisher claims to have copied source code he found at https://github.com/devi/tmp/blob/master/js/bcrypt_pbkdf.js

This makes the license of  https://www.npmjs.com/package/bcrypt-pbkdf unclear
maybe node-sshpk cannot be licensed under MIT?

**Comment by melloc** [comment]
@honzajavorek The original author of the JavaScript code clarified in devi/tmp#1 that the original license of the OpenBSD code is preserved in the JavaScript code. The [package.json](https://github.com/joyent/node-bcrypt-pbkdf/blob/master/package.json) for the package includes the license, `"BSD-3-Clause"`, and the license text and copyright notices are in [index.js](https://github.com/joyent/node-bcrypt-pbkdf/blob/fa2ab3ae9efa15367264151398635a915c7b411d/index.js#L5-L82).  Are you looking for a `LICENSE` file to be added? Or something else?

**Comment by melloc** [comment]
`bcrypt-pbkdf@1.0.2` is now published, with fixes for joyent/node-bcrypt-pbkdf#4 and joyent/node-bcrypt-pbkdf#6, so I'm going to close this issue.

**Comment by honzajavorek** [comment]
Thank you very much! ❤️

All my concerns have been resolved. The package now links to the repository and includes a conventional `LICENSE` file, so tools like [license-checker](https://github.com/davglass/license-checker/) can work with it in bulk. One of the issues was I could not even trace the code repository from the npm package, otherwise I'd probably notice the license in `index.js` previously.
