### ISSUE TITLE
stop using optional deps to fix webpack

### ISSUE THREAD

**Issue by BryanCrotaz** [joyent/node-sshpk#53]
ecc-jsbn and tweetnacl appear to not be optional

**Comment by StefanFeederle** [comment]
My webpack build also fails because it's missing tweetnacl, jsbn and ecc-jsbn.

**Comment by Immortalin** [comment]
Any luck getting this to run on browser?

**Comment by light24bulbs** [comment]
These packages being misclassified is causing compatibility issues with certain build systems.  This is an issue.

**Comment by light24bulbs** [comment]
#55

**Comment by arekinath** [comment]
Do you have a specific error message that might be helpful to figure out what's going on that causes it not to work? The deps `ecc-jsbn`, `tweetnacl` etc that are in `optionalDependencies` are there because `sshpk` very carefully only calls `require()` on them if you use the actual functions that depend on those modules (i.e. you can `require('sshpk')` and it does *not* require any of those modules automatically -- you have to do something like make an ED25519 key and call `.sign()` on it before we `require('tweetnacl')`).

If webpack is not able to deal with the `require()` calls being optional and inside functions, I suggest that would be a bug in webpack, not in this module. But if there's somewhere where we are accidentally causing these modules to be `require()`'d when they aren't actually been used, I would like to know about that so I can fix it.

Sorry this has been sitting open for so long -- browser issues are not really a high priority for me (or the other people at Joyent who have worked on this module), and I can't really offer support for how to use `sshpk` with webpack in general (since I don't use it), but I'm happy to take reports of something more specific, like a `require()` happening when it shouldn't and get them fixed up.

**Comment by light24bulbs** [comment]
@arekinath @BryanCrotaz @Immortalin @StefanFeederle

**Comment by arekinath** [comment]
Merged a change in the latest release based on @light24bulbs PR which moves all these into regular dependencies, and also changes the `require()` calls to just happen at startup (at the top of the files). Thanks!
